package com.liberty_amls;

import java.util.ArrayList;

public class SettingsContainer {
    public float markerSize;
    public double defaultExposure;
    public double landingAlt;
    public boolean landingAllowed;
    public boolean onlyOpticalStabilization;
    public String pidFile;
    public String cameraMatrixFile;
    public String cameraDistortionsFile;
    public String watermarkFile;
    public String webResourcesFolder;
    public String webTemplatesFolder;
    public String blackboxFolder;
    public int frameWidth;
    public int frameHeight;
    public boolean disableAutoExposure;
    public boolean disableAutoWB;
    public boolean disableAutoFocus;
    public String defaultServerHost;
    public int defaultServerPort;
    public int defaultVideoPort;
    public boolean videoStreamEnabledByDefault;
    public boolean blackboxEnabled;
    public int serialReconnectTime;
    public int telemetryLostTime;
    public int platformLostTime;
    public int platformLightEnableThreshold;
    public int platformLightDisableThreshold;
    public int platformReplyTimeout;
    public int platformLoopTimer;
    public int fpsMeasurePeriod;
    public int adaptiveThreshConstant;
    public short arucoDictionary;
    public ArrayList<Integer> allowedIDs;
    public double inputFilter;
    public double setpointAlignmentFactor;
    public int allowedLostFrames;
    public double landingDecrement;
    public double allowedLandingRangeXY;
    public double allowedLandingRangeYaw;
    public double setpointX;
    public double setpointY;
    public double setpointYaw;
    public byte dataSuffix1;
    public byte dataSuffix2;
    public short pushOSDAfterFrames;
}
